### ISSUE TITLE
Goal didn't give reasonable types

### ISSUE THREAD

**Issue by dannypsnl** [aya-prover/aya-dev#1013]
With the following definition

```
def isProp (A : Type) => ∀ (a b : A) -> a = b
def isSet (A : Type) : Type => ∀ (a b : A) -> isProp (a = b)

def is-prop-is-set {A : Type} : isSet (isProp A) =>
  \x y => \a b => {??}
```

- primitives are taken from https://github.com/aya-prover/aya-dev/blob/69b0f2d41673ff0f9115e2ca99fba3f3a1a7fe7b/base/src/test/resources/literate/compiler-output.aya.md?plain=1#L1-L16

Most types in context are holes instead of reasonable things as I expected.

```
Goal: Goal of type
        a = b
        (Normalized: a = b)
      Context:
        {A : Type 0}
        {x : _9}
        {y : _4}
        {a : _6}
        {b : _0}
```

**Comment by ice1000** [comment]
![image](https://github.com/aya-prover/aya-dev/assets/16398479/e73fdf30-3d67-425c-b2e4-b608072955d9)

Fixed
