### ISSUE TITLE
Compile sigma type term

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#1033]
From aya-prover/locally-nameless-aya-draft#74

**Comment by HoshinoTented** [comment]
It would be nice to implement `SigmaTerm` with `Closure` since the `TermExprializer` rejects `LocalTerm` for now.

**Comment by ice1000** [comment]
Let's get rid of built-in sigma term. We use classes with shapes.

**Comment by ice1000** [comment]
It's fixed
