### ISSUE TITLE
Equal Sigma type is not equal

### ISSUE THREAD

**Issue by refparo** [aya-prover/aya-dev#13]
Commit: c7d7714

```aya
open data Unit : Type | unit

def foo : Sig Unit ** Unit => (unit, unit)

def bar : Sig Unit ** Unit => foo
```

**Comment by ice1000** [comment]
I can't believe my eyes

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/133008904-0752913d-f308-4266-a607-b0988cfc6d06.png)
They're elaborated weirdly

**Comment by ice1000** [comment]
Fixed.
