### ISSUE TITLE
Actually useful 'unsolved meta' error message

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#140]
I guess we're gonna add a stack to `Zonker`

**Comment by ice1000** [comment]
```
    ----------------------------------------
      In file D:\git-repos\aya-prover\base\src\test\resources\success\refparo\refparo2.aya:34:40 ->

      32 |   => unit
      33 |
      34 | def bar : Unit => foo getValue setValue value-inv
                                                   ^-------^

    Error: Unsolved meta t'
           in `t'`
           in `value-inv {t'}`
           in `value-inv {t'} {_}`
           in `λ {_} ? value-inv {t'} {_}`
           in `λ {_} ? λ {_} ? value-inv {t'} {_}`
           in `foo {Unit} (λ t ? getValue t) (λ x ? λ t ? setValue x t) (λ {_} ? λ {_}
           ? value-inv {t'} {_})`

    1 error(s), 0 warning(s).
    What are you doing?
```

Do you like what you see?

**Comment by imkiva** [comment]
I think we can only show these instead of all:

```
Error: Unsolved meta t'
           in `t'`
           in `value-inv {t'}`
           in `value-inv {t'} {_}`
```

**Comment by ice1000** [comment]
> I think we can only show these instead of all:
> 
> ```
> Error: Unsolved meta t'
>            in `t'`
>            in `value-inv {t'}`
>            in `value-inv {t'} {_}`
> ```

What's the exact criteria?

**Comment by imkiva** [comment]
> > I think we can only show these instead of all:
> > ```
> > Error: Unsolved meta t'
> >            in `t'`
> >            in `value-inv {t'}`
> >            in `value-inv {t'} {_}`
> > ```
> 
> What's the exact criteria?

_Users can know how to make the code pass_ IMO

**Comment by ice1000** [comment]
> > > I think we can only show these instead of all:
> > > ```
> > > Error: Unsolved meta t'
> > >            in `t'`
> > >            in `value-inv {t'}`
> > >            in `value-inv {t'} {_}`
> > > ```
> > 
> > What's the exact criteria?
> 
> _Users can know how to make the code pass_ IMO

Well, it might be that the meta is the last argument of a huge application. There will be many edge cases I believe
