### ISSUE TITLE
Merge or delete tests for already stabilized features (like parser, etc.)

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-dev#144]
like `emoji-*-.aya`, `syntax.aya`

**Comment by ice1000** [comment]
Duplicate of #29

**Comment by imkiva** [comment]
I mean not only success tests. There are lots of failure tests that make the development harder, for example:
- syntax errors. These tests' `.aya.txt` need to be regenerated every time we change the grammar.
- files with multiple definitions for testing on the same thing. The order of problems reported is not guaranteed

**Comment by ice1000** [comment]
> I mean not only success tests. There are lots of failure tests that make the development harder, for example:
> - syntax errors. These tests' `.aya.txt` need to be regenerated every time we change the grammar.
> - files with multiple definitions for testing on the same thing. The order of problems reported is not guaranteed (maybe it is not a problem of tests)

I agree with you, and I can see the problems too. But how to address the problem?
