### ISSUE TITLE
Use arrays in core instead of `ImmSeq`?

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#189]
Pros:

+ GraalVM easy interop (see @tsao-chi's comment in https://github.com/aya-prover/aya-prover-proto/pull/654#issuecomment-904359358)
+ `Term[]` is shorter than `ImmutableSeq<Term>`
+ [JEP 405](https://openjdk.java.net/jeps/405) makes pattern matching on an entire array possible, and will benefit the 'match the shape of a definition and make it primitive' feature planned in the initial proposal of Aya
+ Kala has a lightweight wrapper for arrays, so we don't lose many conveniences

Cons:

+ Arrays are slightly less safe than `ImmSeq` due to the subtle mutability
+ `@NotNull Term @NotNull []` is a confusing syntax

/cc @imkiva

**Comment by imkiva** [comment]
Since kala has wrappers (both mutable and immutable) I think it's fine.

![image](https://user-images.githubusercontent.com/9902643/141930836-e6857bf8-0168-4511-a947-43aa79c6453f.png)

**Comment by ice1000** [comment]
> Since kala has wrappers (both mutable and immutable) I think it's fine.
> 
> ![image](https://user-images.githubusercontent.com/9902643/141930836-e6857bf8-0168-4511-a947-43aa79c6453f.png)

Noice! Then it's a matter of finding a volunteer to do this... Like myself.

**Comment by ice1000** [comment]
Well, maybe not now. Maybe someone else. I have some other minor things I want to do.

**Comment by imkiva** [comment]
Let me have a try. This seems so easy with a simple Find & Replace (((

**Comment by ice1000** [comment]
> Let me have a try. This seems so easy with a simple Find & Replace (((

May not be _that_ easy. Glhf!
