### ISSUE TITLE
Implement `elim` keyword in Arend

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#215]
I think it is quite useful. We deleted it for early development convenience (https://github.com/aya-prover/aya-prover-proto/issues/219), but probably it's time to change it back.

**Comment by imkiva** [comment]
Let's call this PR `Eliminate Eliminate elim` (https://github.com/aya-prover/aya-prover-proto/pull/221)

**Comment by ice1000** [comment]
Done in new Aya
