### ISSUE TITLE
Respect user options in cli-reporter?

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#223]
https://github.com/aya-prover/aya-dev/blob/b967c39e7ca12a93670c89e165d8ee7f8a9533aa/cli/src/main/java/org/aya/cli/single/CliReporter.java#L28

But this could break the tests.

**Comment by imkiva** [comment]
What about using jline as the output backend (just like REPL) to make output colorful? Like

![image](https://user-images.githubusercontent.com/9902643/143019518-ecccbfe0-9cc9-4dea-8abb-d46c9eae1179.png)

**Comment by ice1000** [comment]
> What about using jline as the output backend in CliReporter (just like REPL) to make output colorful? Like
> 
> ![image](https://user-images.githubusercontent.com/9902643/143019518-ecccbfe0-9cc9-4dea-8abb-d46c9eae1179.png)
> 
> 

Yaaas! This is beautiful. I suppose that the starting point of this would be to modify CliReporter.stdio

**Comment by imkiva** [comment]
But we may still provide `CliReporter.stdio` for test usage.

**Comment by ice1000** [comment]
> But we may still provide `CliReporter.stdio` for test usage.
> 

I am unsure, we can always use jline and fallback to plain stdout for example

**Comment by imkiva** [comment]
It amazing to find that we didn't use CliReporter in tests, LOL
