### ISSUE TITLE
Purge `BinOpCollector`

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#239]
Less global states

**Comment by tsao-chi** [comment]
Could it be a local state just like before https://github.com/aya-prover/aya-dev/commit/e7d9cc55fcb17e90d9424755e99906e07a996a25 ?

**Comment by ice1000** [comment]
@tsao-chi It was extracted because resolution information needs to be serialized. It was in concrete, while we only serialize core. My anticipated solution to this would be to redesign the way we call Problem::describe (like, we pass in an instance of a distiller, which contains the resolution information)

**Comment by ice1000** [comment]
@tsao-chi Currently everything's limited by the stupid design. I'll do this myself, don't worry. I expect a big refactoring
