### ISSUE TITLE
Remove `type` in `Pat`

### ISSUE THREAD

**Issue by tonfeiz** [aya-prover/aya-dev#242]
It seems there are still some places where some specific `Pat`'s types are useful, like in
https://github.com/aya-prover/aya-dev/blob/85e41c5f5098a5685d007f6000f305ad9703397e/base/src/main/java/org/aya/core/pat/PatUnify.java#L49-L53
where `Pat.Bind`'s type is used.

`Pat.Meta` and `Pat.Ctor`'s types are also used, and seems can not be deleted in my opinion(may be incorrect).

So I'm wondering do you mean to delete all types in `Pat`, or maybe save some of them? @ice1000

**Comment by ice1000** [comment]
> So I'm wondering do you mean to delete all types in Pat, or maybe save some of them? @ice1000

I meant all. `PatUnify` is only used in the tycking of patterns, not the evaluation of patterns. Therefore can be dropped _after_ the tycking.

My expectation would be to introduce a 3rd AST for patterns (I propose the interface name `LHS`), which is a version of `Pat` without types and absurd/Meta cases

**Comment by tonfeiz** [comment]
OK, I understand it now. Thanks a lot.

**Comment by ice1000** [comment]
Well. First of all, do we need types of ctor/tuple patterns? Maybe we can remove these first. It should be acceptable to have only bind patterns typed

**Comment by tonfeiz** [comment]
That should be OK. Then I'll try to implement a version of this first.

**Comment by tonfeiz** [comment]
I've met two problems in doing this, and I want to make sure what I intend to do meets your expectation. @ice1000 

1. I remember that you want to replace `Pat` in `Matching` with `Lhs`, however `Conquer` also uses `Matching` and there's also unification process, so I think maybe it's also a type checking process. If so I would make a new `TyckedMatching` class and use it in `Def`s. 
2. `PatMatcher` needs to be refactored to `LhsMatcher`, but as I said it will also be used in type checking process, so it should also accept `Pat` as its argument. Now it shoud accept two types of arguments with almost the same logic. I don't think it's a good idea to implement the logic twice, but I also wonder whether transfer `Lhs` to `Pat` is a good idea because logically speaking it shouldn't happen. 

Sorry it's a bit long, but I think asking in advance is better than fixing it afterwards. :rofl:

**Comment by ice1000** [comment]
1. Is Conquer unifying patterns?
2. I don't know. Maybe you can generate the underlying Lhs of a Pat earlier and use Lhs for matching only

**Comment by ice1000** [comment]
For 1 I guess the answer is yes. However, Conquer happens right during the type checking so

**Comment by tonfeiz** [comment]
> For 1 I guess the answer is yes. However, Conquer happens right during the type checking so

So I could make a new `TyckedMatching`, right?

> 2. Maybe you can generate the underlying Lhs of a Pat earlier and use Lhs for matching only

 Matching process would also happen in type checking process, and I'm not sure whether `Pat` is able to transfer to `Lhs` at that time...But that sounds better than the other ones, so I'll just go this way. Thanks!

**Comment by ice1000** [comment]
> So I could make a new `TyckedMatching`, right?

I prefer renaming `Matching` to `TypedMatching` and name the new one `Matching`.

> Matching process would also happen in type checking process, and I'm not sure whether `Pat` is able to transfer to `Lhs` at that time...But that sounds better than the other ones, so I'll just go this way. Thanks!

`Pat` to `Lhs` only removes information. Why not?

**Comment by tonfeiz** [comment]
> I prefer renaming `Matching` to `TypedMatching` and name the new one `Matching`.

No problem.



> `Pat` to `Lhs` only removes information. Why not?

I'm kind of worried there may still be `Pat.Meta` in the type checking process, which would not be able to transfer to `Lhs`. But I suppose it's fine to fix it if it really happens.

**Comment by ice1000** [comment]
See #283 and #281, closing
