### ISSUE TITLE
How to typecheck `let`-expressions?

### ISSUE THREAD

**Issue by re-xyr** [aya-prover/aya-dev#25]
I've been thinking about the details of this. Firstly, if we don't have `let`-expressions, we only have to detect all definitions at the top-level and submodules and form a dependency graph out of it. However if we have `let`-expressions, I think the solution is like this:

- Detect all top-level definitions and submodule definitions (but not definitions in `let`-expressions);
- Form a dependency graph out of them (note that if some def `C` in some `A` uses `B` then `A` depends on `B` too);
- *When typechecking a definition and we meet a `let`-expression*, we form a dependency graph of *the module of the `let`-expression*, typecheck them, and go on.

Why not directly form a dependency graph out of all definitions, including those in the `let`-expressions?

- We need to ensure that when we typecheck `let`-expressions, the `localCtx` has the variables of the outer definition. 
- Hence, we should not *lift* the definitions of `let`-expressions outside like we did to `module`s; because this way we could not ensure the `localCtx`. We should typecheck them only when we meet them, at that time the `localCtx` will be complete.

Why won't this cause a problem in dependency?

- If the def in `let`-expression depends on another definition outside, then that definition is also depended on by the outer definition of the `let`-expression. So when we check the `let`-expression, its dependencies are all checked too.
- Another definition outside cannot depend on a definition inside `let`-expression at all.

**Comment by ice1000** [comment]
Fixed!
