### ISSUE TITLE
Make prim related states a part of TyckState

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#256]
As title

**Comment by ice1000** [comment]
@imkiva what's the current status of this issue? I kinda forget about what you did in #288 :thinking:

**Comment by imkiva** [comment]
> @imkiva what's the current status of this issue? I kinda forget about what you did in #288 🤔

not started yet. #288 moves resolving of primitives to StmtResolver. This issue is going to construct PrimFactory inside resolver and pass it to the tycker.

**Comment by ice1000** [comment]
> > @imkiva what's the current status of this issue? I kinda forget about what you did in #288 🤔
> 
> not started yet. #288 moves resolving of primitives to StmtResolver. This issue is going to construct PrimFactory inside resolver and pass it to the tycker.

I see ty!
