### ISSUE TITLE
Nest lambda expression and implicit type annotation in func definition

### ISSUE THREAD

**Issue by tonfeiz** [aya-prover/aya-dev#264]
Recently I plan to translate some code in `PLFA` and `Lean`'s tutorial into `Aya`. I believe this is helpful to my understanding of `Aya` and it can also be seen as a test for `Aya`. These may not be serious issues and maybe low priority, but I'll post them for now anyway. 

The following code doesn't type check:
`def fun1 => \x => \y => ifElse (not y) (x + suc zero) (x + suc (suc zero))`

Do we support nest lambda expressions now? 

Another one is:
`def fun3 x => ifElse true (x + suc zero) (x + suc (suc zero))`
The error msg is :
```
40 | def fun3 x => ifElse true (x + suc zero) (x + suc (suc zero))
Error: The name `x` is not defined in the current scope 
```

I'm not sure where the problem is in this one. BTW, if this is out of expectation, I can try to fix it.

**Comment by ice1000** [comment]
> Recently I plan to translate some code in `PLFA` and `Lean`'s tutorial into `Aya`. I believe this is helpful to my understanding of `Aya` and it can also be seen as a test for `Aya`. These may not be serious issues and maybe low priority, but I'll post them for now anyway.

:+1:

> The following code doesn't type check: `def fun1 => \x => \y => ifElse (not y) (x + suc zero) (x + suc (suc zero))`
> 
> Do we support nest lambda expressions now?

I expect this to be fixed by #160 (search `funExt2` in the test library)

> Another one is: `def fun3 x => ifElse true (x + suc zero) (x + suc (suc zero))` The error msg is :
> 
> ```
> 40 | def fun3 x => ifElse true (x + suc zero) (x + suc (suc zero))
> Error: The name `x` is not defined in the current scope 
> ```

Try `def fun3 (x : _) => ...` or `def fun3 => \x => ...`

> I'm not sure where the problem is in this one. BTW, if this is out of expectation, I can try to fix it.

It should be obvious from my above answers. Lmk if you have further questions

**Comment by ice1000** [comment]
Note that #160 is being fixed right now. I expect your code to work with future main branch (after like a few minutes)

**Comment by tonfeiz** [comment]
Don't worry, I'm far from productive :rofl: .  I guess I'll just work on the basis of the future main branch.

**Comment by ice1000** [comment]
> Don't worry, I'm far from productive :rofl: .  I guess I'll just work on the basis of the future main branch.

Does it work?

**Comment by tonfeiz** [comment]
`def fun3 => \x => ...` works while `def fun3 (x : _) => ...` doesn't. The error is
```
def fun3 (x : _) => ifElse true (x + suc zero) (x + suc (suc zero))
              ^^

Error: Unsolved meta _0
```

**Comment by ice1000** [comment]
> `def fun3 => \x => ...` works while `def fun3 (x : _) => ...` doesn't. The error is
> ```
> def fun3 (x : _) => ifElse true (x + suc zero) (x + suc (suc zero))
>               ^^
> 
> Error: Unsolved meta _0
> ```
> 

Try the other code

**Comment by ice1000** [comment]
> `def fun3 => \x => ...` works while `def fun3 (x : _) => ...` doesn't. The error is
> ```
> def fun3 (x : _) => ifElse true (x + suc zero) (x + suc (suc zero))
>               ^^
> 
> Error: Unsolved meta _0
> ```
> 

I think it's fine. What about fun1?

**Comment by tonfeiz** [comment]
`fun1` passed now!

But why is the error of  `fun3` above fine? It seems to be a legal expression to me.

**Comment by ice1000** [comment]
> `fun1` passed now!
> 
> But why is the error of  `fun3` above fine? It seems to be a legal expression to me.
> 

Question: consider the following which works with current behaviour

```aya
def succ Nat : Nat
| a => suc a
```

You're asking `Nat` to be parsed as a binding

**Comment by ice1000** [comment]
Who knows~ not me

**Comment by ice1000** [comment]
> `fun1` passed now!
> 
> But why is the error of  `fun3` above fine? It seems to be a legal expression to me.
> 

It's because signatures and bodies are checked separately. Maybe we should enhance the SCCTycker to disallow recursion in functions with an expression body and check its signature along with its body

**Comment by imkiva** [comment]
> check its signature along with its body

in this case, the `fun3` lives in an SCC which only contains `fun3`. So its body and signature are checked together.

**Comment by ice1000** [comment]
> 

Yes, but can we invoke a special function in this case?

**Comment by imkiva** [comment]
@ice1000 of course. it is pretty simple

**Comment by ice1000** [comment]
@imkiva How to do it? I am clueless
