### ISSUE TITLE
Support rename in open command

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-dev#289]
Proposal: introduce a grammar

```antlr4
primDecl : PRIM ID (AS declNameOrInfix)? tele* type? bindBlock?;
```

**Comment by ice1000** [comment]
@imkiva I agree :)
But I'm still a fan of open import renaming as infix. Wdyt?

**Comment by imkiva** [comment]
> @imkiva I agree :) But I'm still a fan of open import renaming as infix. Wdyt?

Sounds better if we don't want users to introduce primitives directly (instead, users should import stdlib which contains primitive declarations), because we can't _introduce-then-make-it-infix_ in this way.

**Comment by ice1000** [comment]
@imkiva Yeah!!
