### ISSUE TITLE
`rewrite` keyword as in `Agda` and `Coq`?

### ISSUE THREAD

**Issue by tonfeiz** [aya-prover/aya-dev#294]
As title. 

For example, suppose we have `+-comm` and `(p + m) <= (p + n)`, and we want to prove `(m + p) <= (n + p)`. We could just `rewrite` twice in `Agda` and `Coq`. Can we do it in `Aya` like this right now?

**Comment by ice1000** [comment]
@tonfeiz No.

**Comment by ice1000** [comment]
Personally, I don't like `rewrite` as a keyword. It should be a tactic like in Coq or Arend.

**Comment by tonfeiz** [comment]
That's fine, it doesn't have to be a keyword. So we don't have this kind of mechanism now?

**Comment by ice1000** [comment]
@tonfeiz Yes

**Comment by tonfeiz** [comment]
Got it.

**Comment by ice1000** [comment]
In case you're interested https://github.com/JetBrains/arend-lib/blob/master/meta/src/main/java/org/arend/lib/meta/RewriteMeta.java

**Comment by ice1000** [comment]
Also a mad scientist' work https://github.com/agda/agda-stdlib/pull/1658

**Comment by tonfeiz** [comment]
That's great! I'll have look at them. BTW, do we plan to do it in the future?

**Comment by ice1000** [comment]
@tonfeiz Of course, it's a must. Before that we need a good tactic framework, which I guess we can steal some ideas from Lean and Agda. I think Agda has a good tactic framework, but it's been 10 years that nobody's trying to make a set of standard tactics and let everybody use them.

**Comment by ice1000** [comment]
Arend has got a good reference on what tactics should be implemented: https://arend-lang.github.io/documentation/standard-tactics

But I believe the standard tactics of Lean and Coq are more important as they're used by more people so better tested

**Comment by ice1000** [comment]
I'd like to do it in Agda's approach, but first consider dealing with bindings in a dependently typed language... We're about to (or maybe far from -- it all depends on @wsx-ucb) have HOAS in the core, so maybe we can reflect it to the object language. Maybe someone should read https://jesper.sikanda.be/posts/1001-syntax-representations.html

**Comment by tonfeiz** [comment]
That's OK. I'll first have a look at the post when I have time. Then maybe I'll try to learn something about tactic framework. I don't know much about it now.
