### ISSUE TITLE
`forall` syntax for pi types

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#31]
Similar to Agda's `forall`. Also, we may add `exists` for `Sig`.

**Comment by tonfeiz** [comment]
To make sure I'm understanding it correctly, does it mean that

`p : Pi (i : I) -> A i)` can now be written as `p : Pi (forall i) -> A i`, and in essence `i` is just an `Hole` Expr? 

Besides, do we need to use unicode symbol to represent `forall` like Agda?

**Comment by ice1000** [comment]
> To make sure I'm understanding it correctly, does it mean that
> 
> `p : Pi (i : I) -> A i` can now be written as `p : Pi (forall i) -> A i`, and in essence `i` is just an `Hole` Expr? 

No. I expect `p : forall i → A i`, and `i` is never a holeexpr, it's a binding! Its type will be a holeexpr tho.


> Besides, do we need to use unicode symbol to represent `forall` like Agda? 

Yes, let the user choose. See how we support unicode λ, Π, Σ, etc.

**Comment by tonfeiz** [comment]
> No. I expect `p : forall i → A i`, and `i` is never a holeexpr, it's a binding! Its type will be a holeexpr tho.
> 
> >

Do you mean all `Pi` can be ignored, or only when `forall` is used?

**Comment by ice1000** [comment]
> > No. I expect `p : forall i → A i`, and `i` is never a holeexpr, it's a binding! Its type will be a holeexpr tho.
> > 
> > >
> 
> Do you mean all `Pi` can be ignored, or only when `forall` is used?

Only when forall is present.

So basically `forall` is a shorthand of `Pi` with omitted type. This is because if you write `Pi i → j` it means `Pi (_ : i) → j`

**Comment by tonfeiz** [comment]
OK, got it now. Thks :beers:

**Comment by ice1000** [comment]
To make myself even clearer:

+ `x -> y` means `(_ : x) -> y` which means `Pi (_ : x) -> y`
+ `Pi x -> y` means `Pi (_ : x) -> y`
+ `forall x -> y` means `Pi (x : _) -> y`

I also expect `forall x y z -> w` to be desugared in the obvious way.

**Comment by ice1000** [comment]
Note how we change `_ : x` to `x : _` from `Pi` to `forall`

**Comment by tonfeiz** [comment]
OK, thanks for the explanation! 

I've been travelling with my friends these days as it's National Day, so it may take me a longer time to finish this. But anyway, I'll try to do this whenver I'm free~

**Comment by ice1000** [comment]
@tonfeiz Take your time, no hurry!
