### ISSUE TITLE
Completely remove visitors everywhere?

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#315]
My plan of replacing `*Consumer` and `*Fixpoint` is to replace them with an interface of a pattern matching function

```java
interface ExprConsumer<P> {
  default void traverse(Expr expr, P p) {
    switch (expr) {
     // traverse the expr
    }
  }
}
```

Then, we replace the implementations with

```java
class Visitor impl ExprConsumer<P> {
  @Override void traverse(Expr expr, P p) {
    if (expr instanceof BlaExpr bla) { /* do something */ }
    super.ExprConsumer.traverse(expr, p);
  }
}
```

**Comment by imkiva** [comment]
Will the default `traverse` traverse sub trees?

**Comment by imkiva** [comment]
> Will the default `traverse` traverse sub trees?

I think it is yes.

**Comment by ice1000** [comment]
@imkiva Yes

**Comment by ice1000** [comment]
I have an even better idea. Consider fusion of operations on expressions, where when you do `expr.accept(a).accept(b)`, it actually traverse the term twice which is quite unpleasant. Whata bout this:

`expr.visit().accept(a).accept(b).bye()`

`visit` creates something like a view to an expr, then `accept` is like `.map` or `.filter` of a view, which creates a new impl of a view. Then, `bye` performs the operation and gives an `expr` back. By that we only traverse the subject once, and we only need to implement traversal in `bye`. This should make the API much more pleasant to work with, as we don't have to do all those annoying `doAccept` or `accept` things with these.. Tracing will be simply `.visit().traced(tracer)`-ish thingy

/cc @imkiva

**Comment by ice1000** [comment]
Or maybe @wsx-ucb ^

**Comment by wsx-ucb** [comment]
I like the idea but am not sure if I fully understand it. For the example (`expr.visit().accept(a).accept(b)`), are `a` and `b` general visitors that can recursively visit all nodes in the `expr`? If so, how can we interleave them when finally executing with `.bye()` to avoid duplicated traversal?

**Comment by ice1000** [comment]
> I like the idea but am not sure if I fully understand it. For the example (`expr.visit().accept(a).accept(b)`), are `a` and `b` general visitors that can recursively visit all nodes in the `expr`? If so, how can we interleave them when finally executing with `.bye()` to avoid duplicated traversal?

`accept` is a bad name, maybe I should instead use `map` or something. I think this is essentially what's in the Rust standard library (`Iter` and impls) and kala (`SeqView` and subclasses)

**Comment by ice1000** [comment]
```
expr : Expr
expr.visit() : View
expr.visit().map(e) : MapView (implements View)
expr.visit().lift(2) : LiftView (implements View)
expr.visit().bye() : Expr
```

`bye` is like `collect`

**Comment by wsx-ucb** [comment]
I see the parallel with `Iterator<Item=I>`, so is the `Item` here just `Expr`? Lets say once we lazily run a `expr.visit().map(e)`, it just traverse the `Expr` in say depth-first order and pass each visited subtree to `e` right? But if `e` has the type `Expr -> Expr`, we already give `e` the power to look into the entire `Expr` structure of the input (including all subtrees), and hence it make no sense to do a traversal external to `e`. Maybe you mean some other way to design the API for `map`?

**Comment by ice1000** [comment]
@wsx-ucb We don't even need `Item` because `Expr` is not generic. `map : View -> MapView` and `a.map(e) := new MapView(a, e)`

**Comment by wsx-ucb** [comment]
I'm confused now. What is the type of `e` in `a.map(e)`? Is it `Expr -> Expr` or just a generic payload `P` for traversal?

**Comment by ice1000** [comment]
@wsx-ucb `e : Expr -> Expr`

**Comment by ice1000** [comment]
@wsx-ucb Well maybe adding some more parameters but you get the idea

**Comment by wsx-ucb** [comment]
All visitors in `Term` will be removed in #427.
I can also remove that in `GenericDef`.
I guess that's all?

**Comment by ice1000** [comment]
@wsx-ucb I guess so!!
