### ISSUE TITLE
Throw `InternalException` instead of `IllegalXXXException` in tycker

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-dev#343]
So the `AyaCompiler.catching` can make the compiler exit gracefully.

Related #339

**Comment by imkiva** [comment]
Possibly related #328

**Comment by ice1000** [comment]
I agree!

**Comment by ice1000** [comment]
(note: those exceptions all imply bugs in the compiler

**Comment by imkiva** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/9902643/159648192-7ef2e409-58d3-4f7c-b923-0cc1c0a08e8f.png">

**Comment by imkiva** [comment]
<img width="708" alt="image" src="https://user-images.githubusercontent.com/9902643/159648481-fe134d72-f720-4089-8c1a-5bf6d8039538.png">

Gonna run a simple Find & Replace

**Comment by ice1000** [comment]
Sorry

**Comment by lunalunaa** [comment]
I have lots of free time so I'll investigate this.
