### ISSUE TITLE
Using generalized variables in function body and/or function result type crashes the compiler

### ISSUE THREAD

**Issue by refparo** [aya-prover/aya-dev#345]
```aya
open data Unit : Type | unit

open struct Wrapped (A : Type) : Type

variable B : Type

def test Unit : Wrapped B -> Unit
  | unit => \(x : Wrapped B) => unit
```

**Comment by ice1000** [comment]
Will implement later. I think the universe polymorphism problem is more urgent and I want to release it earlier :wink: please understand!

**Comment by lunalunaa** [comment]
New minimally reproducible example for generalized variables appearing in function result type position:

```
variable B : Type

public open data List (A : Type) : Type
| nil
| infixr :< A (List A)

def test : List B => nil

```

Here, `test` should have an implicit variable inserted in the telescope during resolving, but the insertion did not happen.

**Comment by ice1000** [comment]
Yay
![image](https://user-images.githubusercontent.com/16398479/187031925-5095a3df-4973-431e-8b68-e611765627a5.png)

**Comment by lunalunaa** [comment]
> Yay ![image](https://user-images.githubusercontent.com/16398479/187031925-5095a3df-4973-431e-8b68-e611765627a5.png)

Please don't do anything yet. I'm fixing my gpg signature issue

**Comment by ice1000** [comment]
@lunalunaa don't forget to add a test
