### ISSUE TITLE
Ghost story of REPL

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#358]
![image](https://user-images.githubusercontent.com/16398479/160565049-78bf2e8a-56df-45e6-816a-90ac1e06c479.png)

![image](https://user-images.githubusercontent.com/16398479/160565221-0ac955a3-704f-4f14-83fb-cf029907a0db.png)

**Comment by imkiva** [comment]
Ghost story 3: jar-ed REPL keeps throwing IllegalStateException, while the jlinked does not.

![image](https://user-images.githubusercontent.com/9902643/160624737-77ef238a-f530-409a-b5a1-3c070eff6fbb.png)

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/160769485-604b0636-6fff-4683-b65c-934abfba9b92.png)

**Comment by ice1000** [comment]
I suspect it's caused by Java 18. Let's just assume that it is okay
