### ISSUE TITLE
Operator can't contain a colon in the middle

### ISSUE THREAD

**Issue by refparo** [aya-prover/aya-dev#361]
commit: f0964682

Is this expected behavior?

```aya
open import Data::Unit

-- this is OK
def infixr :< Unit Unit => Unit

-- these are parsed as separate tokens
def infixr <:< Unit Unit => unit -- < (:<)
def infixr h:< Unit Unit => unit -- h (:<)

-- this is parsed as an operator and a colon that separates param list and return type
def infixr <: Unit Unit => unit -- < : (Unit Unit)
```

**Comment by ice1000** [comment]
It is expected. Initially we disallowed `:` to be in tokens. Then I've found it very difficult to pick a name for list/vector cons constructor, so I added a special case for that.

**Comment by ice1000** [comment]
It'll be very confusing to have colons in tokens, given that a single colon (and double colons) is already a keyword.

I think the current behavior is fine. I'll be waiting for your counterexample :p

**Comment by ice1000** [comment]
If you intend to make confusing code, try using unicodes. They're very good at confusing people

**Comment by refparo** [comment]
> It is expected. Initially we disallowed `:` to be in tokens. Then I've found it very difficult to pick a name for list/vector cons constructor, so I added a special case for that.

@ice1000 In this case, I would recommend `<|` be used as a cons constructor ([source](https://hoogle.haskell.org/?hoogle=%3C%7C)).

**Comment by ice1000** [comment]
> > It is expected. Initially we disallowed `:` to be in tokens. Then I've found it very difficult to pick a name for list/vector cons constructor, so I added a special case for that.
> 
> @ice1000 In this case, I would recommend `<|` be used as a cons constructor ([source](https://hoogle.haskell.org/?hoogle=%3C%7C)).

Another (bad) reason is that repl needs identifiers starting with `:` to represent commands. So I just made up my mind to allow `:`-identifiers.

`<|` sounds like a legit choice, but I would consider it a pipe operator like in F# ([source](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/#function-symbols-and-operators))

**Comment by ice1000** [comment]
I don't know...
