### ISSUE TITLE
Completely remove `TermFixpoint<P>`

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#365]
Subtask of #315.

Assigned to @wsx-ucb

**Comment by ice1000** [comment]
I also propose removing `Term::subst`, `Term::rename` because these are pointless shortcuts.

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/174505692-8091f980-2f38-4921-ab03-d652c1aa8063.png)

We have only 4 usages left!!

**Comment by tsao-chi** [comment]
What will be used instead of TermFixpoint?

**Comment by ice1000** [comment]
> What will be used instead of TermFixpoint?

New infrastructure.l, might be something based on pattern matching, or just TermView

**Comment by wsx-ucb** [comment]
This is currently taken care of by #427.
