### ISSUE TITLE
Disallow functions without body completely

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-dev#384]
## Background

We used to support this kind of function body in syntax:
```antlr4
fnBody : IMPLIES expr
       | (BAR clause)* ;
```

This implicitly allowed this kind of function `def a : Nat` and we cannot reject it by simply checking whether the `body.isLeft()` or the `body is non-empty right` since there's at least one legal case I can tell:
```
def y (f : Fin zero) : Nat
```

The `Fin zero` does not have any constructor thus no matching is needed, so this decl should tyck.

## Suggested solution
Proposing changing the syntax to: *a function must explicitly have a body, either an expression or a pattern matching*
```diff
fnBody : IMPLIES expr
-       | (BAR clause)* ;
+       | (BAR clause)+ ;
```

and for legal cases, users must explicitly match the param with *impossible*, like:
```
def y (f : Fin zero) : Nat
  | ()
```

**Comment by ice1000** [comment]
If a function has both empty telescope and empty body, then we reject it. Does this work? Because the coverage checker will correctly reject it if it has parameters

**Comment by imkiva** [comment]
> If a function has both empty telescope and empty body, then we reject it. Does this work? Because the coverage checker will correctly reject it if it has parameters

tql. this solution looks much better
