### ISSUE TITLE
Support `let` expression

### ISSUE THREAD

**Issue by lunalunaa** [aya-prover/aya-dev#395]
Syntax:

```haskell
let a := b in c
```

Elaboration and conversion checking shouldn't be too complicated.

- Do not allow `let` to occur everywhere e.g. in declarations, although it actually might be fine

**Comment by refparo** [comment]
Why `:=`?

**Comment by lunalunaa** [comment]
> Why `:=`?

Does not actually matter much.

**Comment by HoshinoTented** [comment]
👀I think this issue can now QED (Quite Eazily Done).
