### ISSUE TITLE
Support {-# FREESIA #-} pragma for termination

### ISSUE THREAD

**Issue by lunalunaa** [aya-prover/aya-dev#397]
[![Watch the video](https://img.youtube.com/vi/Sqx2KT2hbOc/0.jpg)](https://www.youtube.com/watch?v=Sqx2KT2hbOc)

**Comment by imkiva** [comment]
The pragma design: https://github.com/aya-prover/aya-dev/issues/51

**Comment by lunalunaa** [comment]
> The pragma design: #51

Syntactically they all look fine to me, as long as we allow toggling off termination checker.

**Comment by ice1000** [comment]
I'll call it `partial`, same as Lean
