### ISSUE TITLE
Seemingly unsolvable level equation

### ISSUE THREAD

**Issue by refparo** [aya-prover/aya-dev#4]
Aya version: latest build (e4948a9) from GitHub Actions

Code:
```aya
struct TypeStruct : Set
  | type : Set

def setType (type' : Set) (ts : TypeStruct) : TypeStruct
  => new TypeStruct { | type => type' }
```

Got error:
```
In file code/test.aya:5:9 ->

  3 | 
  4 | def setType (type' : Set) (ts : TypeStruct) : TypeStruct
  5 |   => new TypeStruct { | type => type' }
           ^--------------------------------^ TypeStruct.u <= TypeStruct.u

Error: Cannot solve some level equation(s)
```

There seems no way to solve this error.

PS. Will there be a syntax for struct updating like in Idris?
PS2. Will there be partial implementation like in Arend?
PS3. Do my issues feel spamming?

**Comment by ice1000** [comment]
This struct definition should fail:

```aya
struct TypeStruct : Set
  | type : Set
```

Because `Set` is not less than `Set`

**Comment by ice1000** [comment]
I've found the problem. It contains unsatisfiable level equations, but since all levels are _solved_, the error is not reported. Thus an easy fix.

**Comment by ice1000** [comment]
Oh... I've found a very scary bug right now

**Comment by ice1000** [comment]
I have created a PR that rejects your definition of `TypeStruct` in the first place. I have discovered a lot of level-relevant bugs, and have found some other errors in your previous code snippets, so you'd better fix your old code. But kudos for these fantastic discoveries!!

**Comment by ice1000** [comment]
It's now like this:

```aya
-- #2 in public repo
data Entity : Set
  | john

struct EventT : Set 1
  | agentT : Set 0

struct Event (t : EventT) : Set 1
  | agent : t.agentT

data Run (e : Event (new EventT { | agentT => Entity })) : Set
  | (john) => run1

def mkVerb {t : EventT} (p : Event t -> Set 0) : (Event t -> Set 0) -> Set 1
  => \f => Sig (e : Event t) ** (Sig (p e) ** (f e))
```

**Comment by ice1000** [comment]
Checkout the latest version. The level error is reported beforehand now.
