### ISSUE TITLE
Syntax of named arguments clashes syntax of `new`

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#407]
Currently, we use `f {name => value}` for named implicit application.

We also have the syntax:

+ `new Struct { | fieldName => fieldValue }` for creating struct instances
+ `new Struct` for creating empty struct instances

If one forgets about the bar in the braces, say, `new Struct { fieldName => fieldValue }`, this will be considered a `new` expression with the struct type `Struct { fieldName => fieldValue }` (a named implicit application) with no fields.

This can confuse users (this also confused me for several times).

My suggested change is `new Struct {| field => value | field2 => value |}`, where the first bar is optional.

**Comment by ice1000** [comment]
@tsao-chi @imkiva @lunalunaa does this make sense?

**Comment by imkiva** [comment]
What's the error message when missing the first bar? Is it also confusing?

> My suggested change is new Struct {| field => value | field2 => value |}, where the first bar is optional.

But if users forget to write the bar in `{|`, one can still get `Struct { field => value }`?

**Comment by ice1000** [comment]
> What's the error message when missing the first bar? Is it also confusing?

It says you have too many implicit arguments

> But if users forget to write the bar in `{|`, one can still get `Struct { field => value }`? 

No, `{|` and `|}` are keywords and I believe they're easier to memorize (as they appear in pairs)

**Comment by imkiva** [comment]
Are we using `=>` somewhere else? I know function body, named argument, field initializer (correct me if I am wrong).

What about changing named argument to `{name <- value}`? Since '<-' is already reserved, this does not take a builtin token.

**Comment by ice1000** [comment]
> Are we using `=>` somewhere else? I know function body, named argument, field initializer (correct me if I am wrong).

Soon will be used on "restrictions" (something you'll see very soon)

> What about changing named argument to `{name <- value}`? Since '<-' is already reserved, this does not take a builtin token.

Looks good to me but let's ask @lunalunaa and @tsao-chi

**Comment by lunalunaa** [comment]
Another possibility I'd like to suggest is the following:

1. `name := value`

This looks reasonable to me.

> Are we using `=>` somewhere else? I know function body, named argument, field initializer (correct me if I am wrong).
> 
> What about changing named argument to `{name <- value}`? Since '<-' is already reserved, this does not take a builtin token.
> 
> EDIT: looks wired :(

**Comment by ice1000** [comment]
> Another possibility I'd like to suggest is the following:
> 
> 1. `name := value`
> 
> This looks reasonable to me.

Are we also going to use `:=` in more places?

**Comment by lunalunaa** [comment]
> > Another possibility I'd like to suggest is the following:
> > 
> > 1. `name := value`
> > 
> > This looks reasonable to me.
> 
> Are we also going to use `:=` in more places?

no plans for now
