### ISSUE TITLE
Overhaul lifting mechanism

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#440]
0. Only defcalls should be liftable. `RefTerm` is not supposed to be liftable.
1. By that, we can discard the features related to lifting metas.
2. Also, we have a much simpler model of universes.

**Comment by tsao-chi** [comment]
Why is `RefTerm` not supposed to be liftable?

**Comment by ice1000** [comment]
@tsao-chi Consider Lean: only global definitions are allowed to be universe polymorphic, not local variables.

**Comment by tsao-chi** [comment]
@ice1000 Is it a design choice?

**Comment by ice1000** [comment]
@tsao-chi You can say that. I'm sure it has a fairly simple semantics. Allowing rank-n universe polymorphism will make the semantics much more complex, and will be hard to implement (bc holes can be lifted too, hence we need un-lifting to have complete unification).

The original design of the "crude but effective stratification" mechanism we used does not have local lifting. Let's stick to expert's opinion.
