### ISSUE TITLE
Rearrange `Substituter` and `Expander`

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#451]
Currently:

+ `Substituter` literally just replaces `RefTerm` (🤯)
+ `Expander` applies beta reduction and delta reduction

Wanted:

+ `Substituter` replaces terms and applies beta reduction
+ `Expander` applies delta reduction

**Comment by ice1000** [comment]
This seems faulty after some investigations (mostly done by @tsao-chi and @wsx-ucb). However, it is still desirable to have some beta-reduction logic after substitution, bc we are likely to need them. This change is added in an ugly way in #456 and #455 (both merged), and I wish someone can improve the code.

**Comment by wsx-ucb** [comment]
To solve this in the short term, I'll push a version that simply adds another visitor from scratch doing purely beta-reductions.
Admittedly, this introduces code duplication, namely the same beta-reduction logic in `Normalizer`, `WHNFer`, and this new visitor.
To address that, I'm thinking of adding a new helper interface (just like `Expander`) that will encapsulate recursive beta-reduction. (But I haven't come up with a good design yet.)
The intention here is to separate beta- and delta-reduction into separate pieces, and we can later mix and match them to form different reduction strategies.

**Comment by ice1000** [comment]
I think you have to mix them. You're doing beta and eta at the same time.

What about just a pattern matching function?

**Comment by ice1000** [comment]
I think you have to mix them. You're doing beta and eta at the same time.

What about just a pattern matching function?
