### ISSUE TITLE
Replace cofibration syntax with interval expressions

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-dev#452]
#446 added cofibration syntax like
```aya
def partial {A : Type} (a : A) (i : I) : Partial A { i 0 } =>
  {| i 0 := a |}
```

It would be nice if we could make this syntax _customizable_ through _rename as operators_ like:
```aya
open import Primitives using (
  invol as fixl ~
)

def partial {A : Type} (a : A) (i : I) : Partial A { ~ i } =>
  {| ~ i := a |}
```

**Comment by imkiva** [comment]
This may depends on #450 since I want `~ i \/ j` instead of `(~ i) \/ j`

**Comment by ice1000** [comment]
Pinned as this should be prioritized

**Comment by imkiva** [comment]
We may:

1. Remove cofibration syntax from concrete/parser. Instead, use expressions. (let's call them _interval expressions_)
2. During elaboration make sure all _interval expressions_ are judgmentally constant. (in particular, `instanceof PrimTerm.Mula`)
3. Reject all functions that return a type in `ISet`. (done in separate PRs)
4. Add some _facebook_ operations (like tactics) to work with non-trivial cofibration. (done in separate PRs)

**Comment by ice1000** [comment]
For 3, I want to add the condition that functions from I to I should be accepted

**Comment by imkiva** [comment]
Close?

**Comment by ice1000** [comment]
> Close? There's #489 merged

Let's close this in @dark-flames ' branch, as the parsing rules are still there

**Comment by imkiva** [comment]
> > Close? There's #489 merged
> 
> Let's close this in @dark-flames ' branch, as the parsing rules are still there

Okay
