### ISSUE TITLE
Can we make `Partial` a prim instead of a keyword

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#459]
We assign a type to it and elaborate it away.

**Comment by ice1000** [comment]
Similar practice: https://github.com/aya-prover/aya-dev/pull/446/commits/b39bb506f5fc0b958185bf831905492e8a277ee0#diff-abcae851e496b7bff797d135e4a4a5c373b50b422a161a0432403a5df89a9ed9

**Comment by ice1000** [comment]
@tsao-chi @lunalunaa feel free to take over

**Comment by ice1000** [comment]
Also `I` can be a prim`, as long as it's elaborated to `PrimTerm.I`

**Comment by imkiva** [comment]
I remember we once turned I into keyword. What's the rationale converting them back?

**Comment by ice1000** [comment]
> I remember we once turned I into keyword. What's the rationale converting them back?

Because I forgot that you have the choice to elaborate a prim into a special core term and nobody has reminded me that I was being stupid 😭

**Comment by imkiva** [comment]
> > I remember we once turned I into keyword. What's the rationale converting them back?
> 
> 
> 
> Because I forgot that you have the choice to elaborate a prim into a special core term and nobody has reminded me that I was being stupid 😭 

But that's for interval expressions (we want to address syntax conflict of adding cofibration syntax to surface language). We can choose not to do the same for types.

**Comment by ice1000** [comment]
Related to #452
