### ISSUE TITLE
Should we also allow arbitrary dependency order in structs and datas?

### ISSUE THREAD

**Issue by re-xyr** [aya-prover/aya-dev#46]
This means allowing fields/ctors defined later refer to those defined earlier in their types, as what we did to Stmts, as long as the dependency graph forms a DAG.

For structs,
```
struct A : \Type
  | v : T
  | T : \Type
```

For datas,
```
data B (n : N) : \Type \with
  | zero => { | conA (P conC) | conB }
  | suc m => { | conC | conD (P conA) }
```

The case for datas looks more complicated because constructors are intertwined with match clauses.

**Comment by ice1000** [comment]
The plan is:

+ For data ctors, the order is random, but has to be linearizable.
+ For class fields, the order is as written.
+ Records are going to be deleted after classes are implemented
