### ISSUE TITLE
A faithful pretty printer

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#464]
There should be a pretty printer that only adds highlight/links/attributes to the input code, and doesn't change anything in the output. Similar to Agda's literate mode.

Implementation wise, I guess it's something that traverse the tree while holding an iterator of the token sequence. We could start from [SyntaxHighlight.java](https://github.com/aya-prover/aya-dev/blob/279ca6f63dd87da81f1873a9066f6f59bd3217f9/lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java)

**Comment by imkiva** [comment]
Like some RainbowVisitor?

**Comment by ice1000** [comment]
> Like some RainbowVisitor?

Well I'm not sure wdym by rainbow visitor. I think the one in intellij is unrelated

**Comment by imkiva** [comment]
@ice1000 JB's RainbowVisitor uses the same method as you said

**Comment by ice1000** [comment]
@imkiva I see. Seems I don't understand jb as much as you do lol

**Comment by imkiva** [comment]
We already have it: [SyntaxHighlight.java](https://github.com/aya-prover/aya-dev/blob/279ca6f63dd87da81f1873a9066f6f59bd3217f9/lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java)

**Comment by ice1000** [comment]
> We already have it: [SyntaxHighlight.java](https://github.com/aya-prover/aya-dev/blob/279ca6f63dd87da81f1873a9066f6f59bd3217f9/lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java). But it needs some generalization.

Most likely we're going to migrate to GK so it should worth doing this task later

**Comment by imkiva** [comment]
> > We already have it: [SyntaxHighlight.java](https://github.com/aya-prover/aya-dev/blob/279ca6f63dd87da81f1873a9066f6f59bd3217f9/lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java). But it needs some generalization.
> 
> Most likely we're going to migrate to GK so it should worth doing this task later

Are we going to perform annotation together with parsing? If not, this issue might not depend on a GK parser.

**Comment by ice1000** [comment]
> > > We already have it: [SyntaxHighlight.java](https://github.com/aya-prover/aya-dev/blob/279ca6f63dd87da81f1873a9066f6f59bd3217f9/lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java). But it needs some generalization.
> > 
> > Most likely we're going to migrate to GK so it should worth doing this task later
> 
> Are we going to perform annotation together with parsing? If not, this issue might not depend on a GK parser.

The GK parser will surely deprecate the current Aya Lexer I guess

**Comment by ice1000** [comment]
Now we can work on this!!

**Comment by HoshinoTented** [comment]
> We already have it: [SyntaxHighlight.java](https://github.com/aya-prover/aya-dev/blob/279ca6f63dd87da81f1873a9066f6f59bd3217f9/lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java). But it needs some generalization.

`SyntaxHighlight` looks don't add any links.

**Comment by ice1000** [comment]
> > We already have it: [SyntaxHighlight.java](https://github.com/aya-prover/aya-dev/blob/279ca6f63dd87da81f1873a9066f6f59bd3217f9/lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java). But it needs some generalization.
> 
> `SyntaxHighlight` looks don't add any links.

Seems that we need to combine `SyntaxHighlight` and some code in `CoreDistiller`...

**Comment by ice1000** [comment]
It would be nice if we can reuse these code. At least, `SyntaxHighlight` should be reused.

**Comment by HoshinoTented** [comment]
> Seems that we need to combine `SyntaxHighlight` and some code in `CoreDistiller`...

But the `SyntaxHighlither`/`FaithfulDistiller` will work with `Concrete`s instead of `Core`s. However, this is not a serious problem.

**Comment by ice1000** [comment]
I agree. By `CoreDistiller` I probably only mean the pp of those `DefVar`s, which are still present in concrete
