### ISSUE TITLE
Remove `LOR` and `LAND` tokens

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#483]
@imkiva

**Comment by ice1000** [comment]
They are completely useless

**Comment by imkiva** [comment]
We can remove them after #452 and #459 bc they are used in 
![image](https://user-images.githubusercontent.com/9902643/189512939-b40d2029-8c2b-464c-8359-096227fc014f.png)

**Comment by dark-flames** [comment]
Actually, I'm trying to remove `Restr` from concrete to handle this, will this conflict with other branches?
