### ISSUE TITLE
Implement serialization of cubical constructs

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-dev#499]
https://github.com/aya-prover/aya-dev/blob/58fc4b32db750446aa8cc2857a073521edf509f5/base/src/main/java/org/aya/core/serde/Serializer.java#L114-L119

**Comment by ice1000** [comment]
I kinda think these code should be generated. Do you think there's a feasible solution?

**Comment by ice1000** [comment]
Also the whole serialization should be
