### ISSUE TITLE
Leftovers of sort system

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#507]
I think @tsao-chi should have some ideas on how to deal with these. Members should feel free do take these subtasks.

Leftovers:

- [x] tyck rules for top level defs
- [ ] Prop tyck rules
- [x] more Set tyck rules
- [ ] disallow data to live in `ISet` (shall we?)
- [x] #506
- [ ] irrelevance of propositions (that, if `A : Prop` and `a b : A`, then `a = b` definitionally)
- [ ] ~~erasure of propositions (_never_ normalize a term if its type lives in `Prop`)~~
- [x] pattern matching restrictions

_Originally posted by @ice1000 in https://github.com/aya-prover/aya-dev/issues/498#issuecomment-1249585962_

**Comment by SchrodingerZhu** [comment]
how is this going?

**Comment by ice1000** [comment]
@SchrodingerZhu I guess you'd better check the code. I think @tsao-chi did some work on checking `inProp`-ness in pattern matching & expression type checking, but I'm not sure how "complete" they are.

**Comment by ice1000** [comment]
I think @tsao-chi also implemented impredicativity -- that `A : ?, B : Prop ⊢ A -> B : Prop`

**Comment by tsao-chi** [comment]
> I think @tsao-chi also implemented impredicativity -- that `A : ?, B : Prop ⊢ A -> B : Prop`

yes

**Comment by ice1000** [comment]
Closed in favor of #866
