### ISSUE TITLE
Pragma design

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#51]
How do we design pragmas? This is needed for the design of prelude.

**Comment by lunalunaa** [comment]
> + :tada: `@pragma(parameters)`
> 
> + :eyes: `#[inline(parameters)]`
> 
> + :rocket: `%inline parameters`
> 
> + :smile: special comments

~~Breaking the tie~~

**Comment by ice1000** [comment]
> > + :tada: `@pragma(parameters)`
> > 
> > + :eyes: `#[inline(parameters)]`
> > 
> > + :rocket: `%inline parameters`
> > 
> > + :smile: special comments
> 
> ~~Breaking the tie~~

Lmfao 🤣🤣🤣🤣
