### ISSUE TITLE
Pretty print for pathapp/pathlam is huacked up

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#515]
`PathApp(Lam(x, a), b)` rendered as `\x. a b` what the

**Comment by wsx-ucb** [comment]
How can you construct a term like this in the first place?
Lambda followed by a path application?

**Comment by ice1000** [comment]
> How can you construct a term like this in the first place?
> Lambda followed by a path application?

By `new` a core term?

In general, I believe these terms will always be created by buggy elaborator, but the behavior of the pp hides these bugs very well that makes debugging more difficult.

This issue proposes an enhancement, so you gotta mock the terms.
