### ISSUE TITLE
`coe` doesn't check the φ condition

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#522]
![image](https://user-images.githubusercontent.com/16398479/190935645-37c39fa7-27ce-4b97-bb96-f59ddbc0190c.png)

This thing is not checked.

**Comment by ice1000** [comment]
We just need an Aya equivalent of

https://github.com/ice1000/guest0x0/blob/c577c5fe526cba940d7a4be331d5518cc51d5235/base/src/main/java/org/aya/guest0x0/tyck/Elaborator.java#L295-L309

**Comment by lunalunaa** [comment]
Where should we put the check? @ice1000

**Comment by ice1000** [comment]
> Where should we put the check? @ice1000 

Good question, I don't have a good idea. I currently believe that matching a two-arg invocation to coe should be survivable.
