### ISSUE TITLE
Why not use unification

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#528]
https://github.com/aya-prover/aya-dev/blob/25089b867fc15648d82259e39a7b143f739bff2c/base/src/main/java/org/aya/generic/Shaped.java#L33-L56

@imkiva

**Comment by imkiva** [comment]
I was stupid 🥺

**Comment by ice1000** [comment]
Maybe a unifier does not need a reporter..

**Comment by ice1000** [comment]
Oops
![image](https://user-images.githubusercontent.com/16398479/195959379-77e6de30-e7fb-47d9-bede-4247d3ebe746.png)

**Comment by ice1000** [comment]
Ok I reimplemented this feature
