### ISSUE TITLE
Normalize path types

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#530]
It is well-known that `PathP (i. p i =_A q i) r s` is equivalent to `[i j] A { j := s, ~ j := r, i := p, ~i := q }`, is it possible to normalize the former to the latter?

/cc @imkiva @lunalunaa @wsx-ucb

**Comment by ice1000** [comment]
In other words, this is similar to normalizing `[i] ([j] A { j := q i, ~j := p i }) { j := s, ~j := r }` to `[j i] A { j := s, ~ j := r, i := p, ~i := q }`

**Comment by imkiva** [comment]
Where do we need curried Path types?

**Comment by imkiva** [comment]
> Where do we need curried Path types?

like composing a higher dimensional cube without writing the base again and again?

**Comment by ice1000** [comment]
> Where do we need curried Path types?

In Agda, there is no multi-arg path type, so they use this way. Their code is still valid in Aya, so I wonder if we need to translate them into the preferred syntax.

**Comment by ice1000** [comment]
It may cause substitution to be unstable on path type former. Closing.
