### ISSUE TITLE
Cubical subtypes

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#532]
This is a task.

**Comment by lunalunaa** [comment]
Add PrimTerms `inSub`, `outSub`, `Sub` and implement typechecking and computation rules

**Comment by lunalunaa** [comment]
Add PrimTerms `inSub`, `outSub`, `Sub` and implement typechecking and computation rules

**Comment by ice1000** [comment]
Closing for now, because the rules are implemented. Coercions are yet to be done.
