### ISSUE TITLE
Pattern matching on structs causes TyckerException

### ISSUE THREAD

**Issue by refparo** [aya-prover/aya-dev#6]
Commit: beca413

```aya
open data Bool : Set | true | false

struct BoolPair : Set
  | fst : Bool
  | snd : Bool

open data U2 (x : BoolPair) : Set
  | (false, false) => zero
  | (false, true) => one
  | (true, false) => two
  | (true, true) => three

def not2 (x : BoolPair) : BoolPair
  | (false, false) => (true, true)
  | (false, true) => (true, false)
  | (true, false) => (false, true)
  | (true, true) => (false, false)
```

Both the data and the function definition cause the exception.

I don't really know the syntax for pattern matching on structs, so I could only guess it's the same as tuples as in Arend. Replace the parentheses with braces and the issue still occurs.

Judging from the source code, tycking for tuple patterns is not yet completed?

**Comment by tsao-chi** [comment]
https://github.com/aya-prover/aya-dev/blob/5b7bfe38389c2b567db07ae5ca45d03221b6f710/base/src/main/java/org/aya/concrete/Pattern.java#L36

I think there isn't a syntax for that

**Comment by ice1000** [comment]
You should use projections on structs.

**Comment by ice1000** [comment]
We will now report an error for this code (instead of throwing exceptions)

**Comment by refparo** [comment]
But how to use projections in patterns? Sorry if this is a stupid problem.

**Comment by ice1000** [comment]
> But how to use projections in patterns? Sorry if this is a stupid question.

I mean you need to pattern match on `x.fst`, `x.snd`, etc. But then you need to create new functions to pattern match on 'em. Sorry, the syntax is stupid, but we haven't decided on how to implement pattern matching expressions.

**Comment by refparo** [comment]
And this isn't possible in data definitions…

**Comment by ice1000** [comment]
> > …you need to pattern match on `x.fst`, `x.snd`, etc.
> 
> This isn't possible in data definitions…

```aya
open data U2Impl (x y : Bool) : Set
  | false, false => zero
  | false, true => one
  | true, false => two
  | true, true => three

def U2 (x : BoolPair) => U2Impl x.fst x.snd
```
