### ISSUE TITLE
Viewing the migration in retrospect

### ISSUE THREAD

**Issue by re-xyr** [aya-prover/aya-dev#60]
Because of the incidents and lack of communication during this migration, and also that both @ice1000 and I feel bad about certain parts of it, I feel this is necessary. This retrospective view can serve as a proposal of collaboration guideline.

Problems:

- Prior to migration, no clear plan or consensus has been reached anyhow because of my lack of communication. As a result, @ice1000 had to decide the whole plan on himself, despite the complexity, pressure and great details in the migration. I failed to contribute to the collaborative effort; this is highly irresponsible of me.
- All the forks were removed because @ice1000 felt a need of shrinking the space the repo occupies and clearing the commit history.
  - Even though we generally do not accept PRs for now, this can still cause damage to some potential contributions that may be happening in the forks.
  - The ~2000 commits occupies ~5MB space which is neither significant to disk storage nor bandwidth.
  - Wiping out the commit history is unnecessary and yet was decided to be a must-do, which is persumably the main reason of removing all the forks.
- We lost the stars because of a switch from public to private visibility.
  - Obviously, both @ice1000 and I see this as a very bad consequence.
  - Risk of losing all forks and stars is clearly shown in the confirmation of changing repo visibility, and @ice1000 either ignored it or deemed it acceptable without consulting other members.

With that said, none of those can be reverted. This is why I have the following suggestions of preventing such bad, irreversible situations from happening again:

- I suggest that in the future, before this kind of major changes, all core contributors must work towards a consensus, no matter how long it takes, modulo very emergent situations (which is unlikely). Each core contributor should remind others too.
- Transferring repository and changing repository visibility are highly risky actions and should not be done unless really necessary.
  - The consequences of doing so can be serious, so it must also be agreed upon by all core contributors.
  - "Clearing forks" is hardly a valid reason for changing repository visibility, as there is often only bad effects by clearing all forks.
    - Most of the times, a better choice is to archive the repository and creating a new one.

Initially, I wanted to say that this issue "is not to blame anyone," but that is wrong. We need to "blame," i.e. establish the responsibility of every contributor in this event and similar future ones so that we can make the best out of collaborative effort.

**Comment by ice1000** [comment]
@re-xyr I agree with everything. I think this can be slightly modified and put into some CONTRIBUTING.md or CODE_OF_CONDUCT.md? These files can be put into .github folder so we don't have a huge root dir.

**Comment by re-xyr** [comment]
I think it should be `CONTRIBUTING.md`. `CODE_OF_CONDUCT.md` is mainly for ethics requirements.

**Comment by ice1000** [comment]
> I think it should be `CONTRIBUTING.md`. `CODE_OF_CONDUCT.md` is mainly for ethics requirements.

Can you do it?

**Comment by ice1000** [comment]
It should be mostly copying and pasting this post, I guess.

**Comment by re-xyr** [comment]
I think not really, since we do not want to include information about incidents in the contributing guideline? It seems irrelevant.

**Comment by ice1000** [comment]
@re-xyr What about these?

- I suggest that in the future, before this kind of major changes, all core contributors must work towards a consensus, no matter how long it takes, modulo very emergent situations (which is unlikely). Each core contributor should remind others too. 
- Transferring repository and changing repository visibility are highly risky actions and should not be done unless really necessary. 
  - The consequences of doing so can be serious, so it must also be agreed upon by all core contributors.

**Comment by ice1000** [comment]
@ice1000 Well I think these are kinda obvious

**Comment by ice1000** [comment]
@ice1000 Maybe they don't worth writing about, since we probably won't do that again

**Comment by re-xyr** [comment]
> Maybe they don't worth writing about, since we probably won't do that again

I don't think so. Human beings can behave very weird from time to time.

I will rephrase that part and add those into the `CONTRIBUTION.md`. I will make a first draft, and I encourage all contributors to add necessary guidelines into it. I will also create a `CODE_OF_CONDUCT.md` for our  ethics baseline, per the [Contributor Covenant](https://www.contributor-covenant.org/).

**Comment by tonyxty** [comment]
You might want to find a way to revert that.  Your repository contains my contributions without a proper credit to me.  You might be violating my copyright here, and might risk a DMCA takedown.

**Comment by ice1000** [comment]
> You might want to find a way to revert that. Your repository contains my contributions without a proper credit to me. You might be violating my copyright here, and might risk a DMCA takedown.

It's archived: https://github.com/aya-prover/aya-prover-proto

If you think this is improper then I will delete the files you created and I copied from the other repo.

**Comment by ice1000** [comment]
Btw I don't think it's a good idea to instigate irrelevant people such as cloudifold to laugh at me on the migration. She had the chance to stop me as well but when I was asking about a meeting on the decision, nobody responded for at least two days (including a Sunday -- a weekend day, and a Monday -- a weekday), so I said 'ok, so probably we don't need a meeting, probably nobody's interested in seeing me publicizing the private repo/transferring issues/setting up bors, I can just do it myself'.

**Comment by ice1000** [comment]
Anyways, since I don't want to have trouble with DMCA, I'll sanitize the repo myself.

**Comment by re-xyr** [comment]
@tonyxty Your contributed files include:

- `docs/src/demo/Foundation.mzi`
- `docs/design-choices.md`
- `docs/src/priority.md`
- `docs/src/mathmaticians-expectation-of-pa/00-some-algebra.md`
- `docs/src/mathmaticians-expectation-of-pa/01-class-system.md`

We can remove these files in this repository and in the archived repository if you want that.

**Comment by tonyxty** [comment]
> @tonyxty Your contributed files include:
> 
>     * `docs/src/demo/Foundation.mzi`
> 
>     * `docs/design-choices.md`
> 
>     * `docs/src/priority.md`
> 
>     * `docs/src/mathmaticians-expectation-of-pa/00-some-algebra.md`
> 
>     * `docs/src/mathmaticians-expectation-of-pa/01-class-system.md`
> 
> 
> We can remove these files in this repository and in the archived repository if you want that.

You may remove the files in this repo.  You can keep the files in the archived repo.

> Btw I don't think it's a good idea to instigate irrelevant people such as cloudifold to laugh at me on the migration. She had the chance to stop me as well but when I was asking about a meeting on the decision, nobody responded for at least two days (including a Sunday -- a weekend day, and a Monday -- a weekday), so I said 'ok, so probably we don't need a meeting, probably nobody's interested in seeing me publicizing the private repo/transferring issues/setting up bors, I can just do it myself'.

I don't know what you're talking about.  Blame whomever you want, explain however you like, I don't know how you get the idea of "instigate irrelevant people to laugh at you."  On the other hand, I do think the aya community deserves a more responsible & sensible leader, not someone who has limited ability at programming language design & project management.

**Comment by ice1000** [comment]
I think we need a leader who commits some time to the development. Apparently, nobody's working on this project with at least several commits weekly except me.

**Comment by ice1000** [comment]
I deleted the files according to your reply. Please use email if you have further requests. I don't wanna see you again in this issue tracker.

**Comment by re-xyr** [comment]
> Btw I don't think it's a good idea to instigate irrelevant people such as cloudifold to laugh at me on the migration

It is not good that you accuse a person of an entirely hypothetical behavior *in public*.

**Comment by ice1000** [comment]
> It is not good that you accuse a person of an entirely hypothetical behavior _in public_.

I agree, probably I shouldn't say that. Would you mind removing your comment? I think it's improper and I don't want to make it publicly visible anymore.
