### ISSUE TITLE
Unifying Owner Telescope

### ISSUE THREAD

**Issue by HoshinoTented** [aya-prover/aya-dev#607]
For the simple data types, the owner telescopes of their constructors are trivial: the data telescope. But the indexed data types are not, the owner telescopes of their constructors depend on the bindings of each pattern. For example:

```aya
open data Vec Type Nat
  | A, zero => vnil
  | A, suc n => vcons A (Vec A n)
```

The owner telescope of `vnil` is `(A : Type)` (size = 1); But for `vcons`, it is `(A : Type) (n : Nat)` (size = 2).

However, we implemented this incorrectly (see [CallTerm.Data#conHead](https://github.com/aya-prover/aya-dev/blob/66b0d8ba3b/base/src/main/java/org/aya/core/term/CallTerm.java#L68), [PatToTerm.java](https://github.com/aya-prover/aya-dev/blob/66b0d8ba3b/base/src/main/java/org/aya/core/pat/PatToTerm.java#L40) )

This should be a potential bug.

**Comment by ice1000** [comment]
Have you fixed this

**Comment by HoshinoTented** [comment]
Did not

**Comment by ice1000** [comment]
> I am not sure because of the refactoring
> 

What refactoring

**Comment by HoshinoTented** [comment]
> > I am not sure because of the refactoring
> 
> What refactoring

renaming

**Comment by HoshinoTented** [comment]
https://github.com/aya-prover/aya-dev/blob/d90261aae5675f16890b02bb0fb673b4f0f6e52f/base/src/main/java/org/aya/core/term/DataCall.java#L13-L22

A bug here, `PatTycker` and `PatClassifier` used this method, but `PatTycker` didn't use the `ConHead#dataArgs`.

**Comment by ice1000** [comment]
> but `PatTycker` didn't use the `ConHead#dataArgs`.

Where is it?

**Comment by ice1000** [comment]
I mean the code

**Comment by HoshinoTented** [comment]
in `PatTycker`, line 511:

https://github.com/aya-prover/aya-dev/blob/eb94294b55b7e39bf3f89c3a9fa550301d6e8016/base/src/main/java/org/aya/tyck/pat/PatTycker.java#L508-L515

in `PatClassifier`, line 316 (which is clearly a bug):

https://github.com/aya-prover/aya-dev/blob/eb94294b55b7e39bf3f89c3a9fa550301d6e8016/base/src/main/java/org/aya/tyck/pat/PatClassifier.java#L314-L318

**Comment by ice1000** [comment]
Why do you think so? Did you mean I should not use `conTele2`?

**Comment by ice1000** [comment]
My brain stops working and I need some help 🥺

**Comment by HoshinoTented** [comment]
> Why do you think so? Did you mean I should not use `conTele2`?

I mean `conHead` construct a `ConHead` with just `DataCall#args` which is buggy. For example:

```aya
open data Vic (n : Nat)
| O => vnil
| S n' => vcons (Vic n')
```

If you want to construct a `ConHead` of `vcons` for some `DataCall`: `Vic (S O)`, it should be `vcons {O}` instead of `vcons {S O}`.

PatTycker didn't use the wrong `ConHead#args`, but `PatClassifier` (which I am not familiar with) might use.

**Comment by imkiva** [comment]
Is this issue related to https://github.com/aya-prover/aya-dev/issues/243? The code below is failing due to the error:
```aya
open data Nat | zero | suc Nat
open data Vec (n : Nat) (A : Type) : Type
| zero, A => vnil
| suc n, A => infixr vcons A (Vec n A)

def last {A : Type} {n : Nat} (Vec (suc n) A) : A
| x vcons vnil => x
| _ vcons xs => last xs
```

```
In file test.aya:8:21 ->

  6 | def last {A : Type} {n : Nat} (Vec (suc n) A) : A
  7 | | x vcons vnil => x
  8 | | _ vcons xs => last xs
                           ^^

Error: Cannot check the expression
         xs
       of type
         Vec <{n}> A
         (Normalized: Vec n A)
       against the type
         Vec (suc n') A'
         (Normalized: Vec (suc n') A)
       In particular, we failed to unify
         n
       with
         suc n'

```

**Comment by ice1000** [comment]
> Is this issue related to https://github.com/aya-prover/aya-dev/issues/243? The code below is failing due to the error:

No

**Comment by ice1000** [comment]
I spent 3 hrs debugging this and there is finally a clue. See branch xyy.

**Comment by HoshinoTented** [comment]
Related branches: [xyy](https://github.com/aya-prover/aya-dev/tree/xyy), [more-terms](https://github.com/aya-prover/aya-dev/tree/more-terms)
