### ISSUE TITLE
Build failure on Ubuntu 20.04 with liberica-17

### ISSUE THREAD

**Issue by re-xyr** [aya-prover/aya-dev#61]
Repro: Build the project on Ubuntu 20.04, with liberica-17 and IDEA 2021.2.2.

Error: 

```
> Task :buildSrc:generateGrammarSource UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:generateTestGrammarSource NO-SOURCE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:copyModuleInfo UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :pretty:compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':pretty:compileJava'.
> 错误: 不支持发行版本 17
```

Fix: Add this to the `java` block in `build.gradle.kts`:

```kotlin
toolchain {
  languageVersion.set(JavaLanguageVersion.of(17))
}
```

I don't know why this is the case though, and why others are not encountering this problem.

**Comment by ice1000** [comment]
In case you have a gradle.properties at the root directory, try putting `org.gradle.java.home=path/to/java/home` (no `bin`, just the root dir of jdk) instead of setting the toolchain. IIRC setting the toolchain makes gradle download its own jdk.

**Comment by re-xyr** [comment]
> try putting org.gradle.java.home=path/to/java/home

I have tried to set the Java home path, it didn't help with the build failure. 

> IIRC setting the toolchain makes gradle download its own jdk.

I think it searches for local JDKs first: https://docs.gradle.org/current/userguide/toolchains.html#sec:consuming

**Comment by re-xyr** [comment]
And actually, you can even specify JDK vendors:

```kt
toolchain {
  languageVersion.set(JavaLanguageVersion.of(17)
  vendor.set(JvmVendorSpec.BELLSOFT)
}
```

When I set this to `BELLSOFT` it correctly chooses my local libericajdk and downloads another one if I changed it to another vendor.

**Comment by ice1000** [comment]
@re-xyr This is awesome. I will approve if you wanna push this code to upstream

**Comment by imkiva** [comment]
> and why others are not encountering this problem.

I have my `JAVA_HOME` explicitly set to liberica-17 in `.zshrc` so that might be the reason I guess.

**Comment by imkiva** [comment]
> @re-xyr This is awesome. I will approve if you wanna push this code to upstream

But our users may not be using liberica as their vendor.

**Comment by ice1000** [comment]
> > @re-xyr This is awesome. I will approve if you wanna push this code to upstream
> 
> But our users may not be using liberica as their vendor.

I'm talking about the code other than setting up the vendor.
