### ISSUE TITLE
Investigate @imkiva's "is it a bug?"

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#636]
Is this a bug?

_Originally posted by @imkiva in https://github.com/aya-prover/aya-dev/pull/633#discussion_r1014647012_

**Comment by tsao-chi** [comment]
What is it?

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/208599695-62683e8c-e83c-4bc0-a998-790b2fc74319.png)

That we no longer lifted this and we did not need to

**Comment by ice1000** [comment]
Deprecated due to the redesign of `coe`
