### ISSUE TITLE
Hiatus

### ISSUE THREAD

**Issue by re-xyr** [aya-prover/aya-dev#64]
In short, I will be on hiatus from Aya's development. I am sorry about this, and I know I haven't been very active for a relatively long period, but I think I should articulate this more clearly. There are several reasons:

- Java code is really hard to deal with. Even with the features in Java 17, there can quickly be verbose and/or imperative code. I just cant motivate myself enough to the level of dealing with similar Haskell or even Kotlin code.
- The migration is emotionally draining. It made everyone feel bad, and even involved some personal relationship conflicts. This is particularly bad for a community. Although others and I were trying to make the situation better in the future, it was still stressful for me.
- I am busy preparing for my college application. This includes preparing exams from 3 (!) different exam boards and a lot of essay writing.

I don't know when I can be again mentally stable enough to return to the development, but I hope it can be around January. I am sponsored by PLCT, and going on hiatus would mean that I failed to meet their expectation. @ice1000 can require me to hand on any sponsorship I receive from PLCT during that period.

**Comment by ice1000** [comment]
@re-xyr I'll talk about this privately with you. I have some ideas and we should have a discussion.
