### ISSUE TITLE
@imkiva's opinions

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#657]
@imkiva said we are not using the `Stylist` interface the right way. So we should listen to and worship @imkiva's opinions.

**Comment by HoshinoTented** [comment]
I NEED IMKIVA'S OPINIONS!!

**Comment by imkiva** [comment]
I NEED IMKIVA'S OPINIONS too!! Can you help help me?

![image](https://user-images.githubusercontent.com/9902643/201954781-30a9cdb6-673c-46fe-84b8-fa0a4d49791a.png)

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/202775874-035c977f-aa3e-41ee-892f-80709a57a4bc.png)

Colors are back
