### ISSUE TITLE
Change comment syntax

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#676]
Do anybody want to take this?

**Comment by ice1000** [comment]
Goal: change `--` + `{-`/`-}` to `//` and `/*`/`*/`. This is closer to the traditional C/C++/Java/Rust experience.

Impl: I expect only changing the lexer and the tests.

**Comment by wsx-ucb** [comment]
We will lost the syntactic coincidence of presenting a function signature as a typing rule (e.g. the style in https://plfa.github.io/Equality/#cong).
But maybe this is not the *Aya style* anyway.

**Comment by ice1000** [comment]
You can use `// --------` I don't think this is going to hurt that much
