### ISSUE TITLE
Adding/moving a directory in VSCode confuse the LSP

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#684]
Very easy to reproduce.

**Comment by imkiva** [comment]
VSCode does not send a file system event when adding/moving a directory?

**Comment by imkiva** [comment]
It looks like design problem: https://github.com/microsoft/language-server-protocol/issues/742

**Comment by imkiva** [comment]
`"workspace/didChangeWorkspaceFolders"`

**Comment by ice1000** [comment]
Does the moved files trigger some notifications?

**Comment by ice1000** [comment]
https://github.com/microsoft/vscode/issues/60813#issuecomment-429854244

They said they trigger folder change events

**Comment by imkiva** [comment]
> https://github.com/microsoft/vscode/issues/60813#issuecomment-429854244
> 
> 
> 
> They said they trigger folder change events

It also says "instead of the files within". So we have to manually list files and process the removal and creation.

And it requires a glob pattern "**/*" (watches everything). But this "everything" does not include external changes like git.

So I suppose we will have a file system watcher to watch files without such "optimizations" and also works for external changes.

**Comment by imkiva** [comment]
> Does the moved files trigger some notifications?

Moving a file triggers a file deletion followed by a file creation.

Moving a directory does not trigger file events. But I expect them to be a list of file deletion, a list of file creation, and a move of the directory (a move event makes fixing directory references easier).

**Comment by ice1000** [comment]
> > [microsoft/vscode#60813 (comment)](https://github.com/microsoft/vscode/issues/60813#issuecomment-429854244)
> > They said they trigger folder change events
> 
> It also says "instead of the files within". So we have to manually list files and process the removal and creation.
> 
> And it requires a glob pattern "**/*" (watches everything). But this "everything" does not include external changes like git, according to [microsoft/language-server-protocol#742 (comment)](https://github.com/microsoft/language-server-protocol/issues/742#issuecomment-771467335)
> 
> So I suppose we will have a file system watcher to watch files without such "optimizations" and also works for external changes.

Yeah.... But I would ask for an option to disable it. It sounds like a disk killer.

**Comment by imkiva** [comment]
> Yeah.... But I would ask for an option to disable it. It sounds like a disk killer.

Yes...
