### ISSUE TITLE
Gson -> jackson

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#685]
This also includes upgrading the upstream dependencies to use jackson, including javacs

**Comment by tsao-chi** [comment]
Why Jackson

**Comment by ice1000** [comment]
> Why Jackson

Gson has some bugs and is not customizable. Gson thinks of enums as strings in serialization while not in deserialization. I don't want to debug their code but instead I think jackson should be better.

Kala planned (long time ago) to use jackson over gson, so if we want to keep using Gson, we need to implement kala-gson as a new project and _maintain_ it.

**Comment by ice1000** [comment]
I think @Glavo gave up jackson and embraced GSON.
