### ISSUE TITLE
Pretty printing for unary application is wrong

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-dev#687]
![image](https://user-images.githubusercontent.com/9902643/202636769-c033fa79-95cc-4e6a-b5fa-40e77cc20e7c.png)

**Comment by tsao-chi** [comment]
test.aya
```

data False

def fixr ¬ (A : Type) => A -> False

def elim {A : Type} False : A | ()
def NonEmpty (A : Type) => ¬ ¬ A

```

![image](https://user-images.githubusercontent.com/57285379/204090005-7b67d022-e1ab-4242-85e3-42bf4f63793c.png)

**Comment by tsao-chi** [comment]
related to this pr https://github.com/aya-prover/aya-dev/pull/476
