### ISSUE TITLE
Confusing scope control modifiers -- `private public open data`

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-dev#690]
According to our grammar, we support:

```aya
private public open data Nat
  | zero
  | suc Nat
```

which looks so confusing!

**Comment by ice1000** [comment]
Is this a proposal of renaming the keyword `public`?

**Comment by ice1000** [comment]
How about `export`?

**Comment by ice1000** [comment]
How should `private public open data` work?

**Comment by HoshinoTented** [comment]
So, we have:
* `public open data`: a non-private data with `public open`
* `private open data`: a private data with `private open` or just `open`
* `open data`: a non-private data with `private open` or just `open`
* `data`: a non-private data with no `open`

**Comment by ice1000** [comment]
I think we shouldn't have that. Essentially we have 2 objects (data & con) and their scope has to be controlled separately. So it's inevitable to have those many options.

+ Data can be exported or not exported -- `data` and `private data`
+ Cons can be opened or kept -- `open` and ø
+ Opened cons can be exported or not exported -- `public` and ø

This makes it simpler.

**Comment by refparo** [comment]
The user can always import the data and then open it?

**Comment by HoshinoTented** [comment]
> I think we shouldn't have that. Essentially we have 2 objects (data & con) and their scope has to be controlled separately. So it's inevitable to have those many options.
> 
> * Data can be exported or not exported -- `data` and `private data`
> * Cons can be opened or kept -- `open` and ø
> * Opened cons can be exported or not exported -- `public` and ø
> 
> This makes it simpler.

So `(public? open)? private? data` ?

**Comment by HoshinoTented** [comment]
> I think we shouldn't have that. Essentially we have 2 objects (data & con) and their scope has to be controlled separately. So it's inevitable to have those many options.
> 
> * Data can be exported or not exported -- `data` and `private data`
> * Cons can be opened or kept -- `open` and ø
> * Opened cons can be exported or not exported -- `public` and ø
> 
> This makes it simpler.

So, `(public? open)? private? data` ?

**Comment by ice1000** [comment]
I think it would be good to have only `(private | open)+` and uniquify them later.
