### ISSUE TITLE
Recognize `Fin` instances as nat literals too?

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#706]
@imkiva any ideae?

**Comment by imkiva** [comment]
Actually there's a `Fin` shape from the very beginning, but I gave up when I need to create a `Nat` where a representation of `Fin` is needed. But I am not sure if it becomes simpler with `MetaLit` now. Will give it a try.

**Comment by ice1000** [comment]
@imkiva You just have to generate `fsuc a` instead of `suc a`, but this has to be a _concrete_ syntax.

**Comment by HoshinoTented** [comment]
One possible problem is type inferring, we won't infer `114514 : {?}` to `114514 : Fin 0`.

**Comment by ice1000** [comment]
lmao yeah

**Comment by ice1000** [comment]
We should do index erasure in an IR and run the shape matcher again. `Vec` will be matched with `List` and `Fin`/`∈` will be matched with `Nat`.

**Comment by ice1000** [comment]
Too hard
