### ISSUE TITLE
Unwilling to normalize definitions

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#726]
![image](https://user-images.githubusercontent.com/16398479/203672047-0676489d-2628-4a50-abf7-09782b127383.png)

**Comment by ice1000** [comment]
Here, I would like to mark the `=` function as an 'unwilling to normalize' definition, and hence in the error messages, the 'normalized' terms will not be normalizing them.

(But still unhelpful for these defs, I have to admit)

**Comment by ice1000** [comment]
I think it depends on #51

**Comment by imkiva** [comment]
Did you mean `def opaque`?

**Comment by ice1000** [comment]
> Did you mean `def opaque`?

That's _absolutely not_ normalizing definitions. It never work! I am thinking about making opaque definitions less opaque in the conversion checker though...

**Comment by ice1000** [comment]
If it works then we won't need this anymore.

**Comment by ice1000** [comment]
The original problem is no longer a problem for us, but still this feature might be useful

**Comment by ice1000** [comment]
Actually I don't see how unwilling they could be, and definitions are already unnormalized as possible.
