### ISSUE TITLE
Do we really need to reuse tyckers?

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#729]
bors r+

**Comment by ice1000** [comment]
https://github.com/aya-prover/aya-dev/blob/a88f24fab955edb262bdbed618723f0f88973c2d/base/src/main/java/org/aya/tyck/order/AyaSccTycker.java#L53

**Comment by tsao-chi** [comment]
Maybe it is needed for keeping `ExprTycker.state`?

**Comment by tsao-chi** [comment]
I tried to remove tyckerReuse

```

  [Tyck] Spaces::Torus::T2-HoTT (Spaces/Torus/T2-HoTT.aya)
org.aya.generic.util.InternalException: i
	at org.aya.tyck.env.LocalCtx.get(LocalCtx.java:104)
```

```
:: Running tests under /home/dev/projects/aya-dev/base/src/test/resources/failure
org.aya.generic.util.InternalException: i
	at org.aya.tyck.env.LocalCtx.get(LocalCtx.java:104)
```

**Comment by ice1000** [comment]
> I tried to remove tyckerReuse
> 
> ```
> 
>   [Tyck] Spaces::Torus::T2-HoTT (Spaces/Torus/T2-HoTT.aya)
> org.aya.generic.util.InternalException: i
> 	at org.aya.tyck.env.LocalCtx.get(LocalCtx.java:104)
> ```
> 
> ```
> :: Running tests under /home/dev/projects/aya-dev/base/src/test/resources/failure
> org.aya.generic.util.InternalException: i
> 	at org.aya.tyck.env.LocalCtx.get(LocalCtx.java:104)
> ```

Of course you'll need to recover the scopes, but that's very easy: whatever is in the localCtx of ExprTycker, you should have them from the telescope of either the telescope or the patterns. So you need to add these variables to the scope, and I guess that's what you're missing. May I have your branch? Or you can do it yourself.
