### ISSUE TITLE
Wrongly placed `DistillOptions`

### ISSUE THREAD

**Issue by SchrodingerZhu** [aya-prover/aya-dev#795]
It has been placed into `tools` package.

**Comment by imkiva** [comment]
Oh we used `DistillerOptions` in reporters....

**Comment by ice1000** [comment]
Then I think we should put the reporters in base as well. They are Aya-specific.

**Comment by imkiva** [comment]
> Then I think we should put the reporters in base as well. They are Aya-specific.

They are quite general and useful for compilers except for `DistillerOptions`.

**Comment by ice1000** [comment]
I agree. Maybe we should make `DistillerOptions` generic too -- make the `Key` generic, and make `AyaDistillerOptions`. But it's up to you.

**Comment by imkiva** [comment]
> I agree. Maybe we should make `DistillerOptions` generic too -- make the `Key` generic, and make `AyaDistillerOptions`. But it's up to you.

Exactly. You again read my mind! 😉

**Comment by imkiva** [comment]
Fixed in #794
