### ISSUE TITLE
Kill the little typer and type annotation in lambda params

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#839]
+ Lambda params are not supposed to be given types
+ They are used in little typer to synthesize types
+ Little typers are only used in `ide` and in unification (check the solution of types)
  + For `ide` we can store types in the concretes instead!
  + For unification, we can use a core type checker which _gives_ us the types!
+ This can save memory consumption

**Comment by HoshinoTented** [comment]
What is `Lambda params are not supposed to be given types` ? Does it mean we can have only `\ x => ...` ?

**Comment by tsao-chi** [comment]
> * Little typers are only used in `ide` and in unification (check the solution of types)

What about `isPropType()`?

**Comment by ice1000** [comment]
> What is `Lambda params are not supposed to be given types` ?

Well, it's a reference to the "Stop doing Math" meme.

> Does it mean we can have only `\ x => ...` ?

No, we can use annotated lambdas to do "infer" for lambdas, but in core, they get removed (and the type is still in `Result::type`)

**Comment by ice1000** [comment]
> > * Little typers are only used in `ide` and in unification (check the solution of types)
> 
> What about `isPropType()`?

Well, we can have another `LittleTyper` that only works for type expressions.

**Comment by HoshinoTented** [comment]
> > What is `Lambda params are not supposed to be given types` ?
> 
> Well, it's a reference to the "Stop doing Math" meme.
> 
> > Does it mean we can have only `\ x => ...` ?
> 
> No, we can use annotated lambdas to do "infer" for lambdas, but in core, they get removed (and the type is still in `Result::type`)

Oh, I see. the concrete typed lambda: `\(x : X) => x` will be separated to a core lambda `\x => x` and a type `Pi X -> X`. Is it right?

**Comment by ice1000** [comment]
> > > What is `Lambda params are not supposed to be given types` ?
> > 
> > Well, it's a reference to the "Stop doing Math" meme.
> > 
> > > Does it mean we can have only `\ x => ...` ?
> > 
> > No, we can use annotated lambdas to do "infer" for lambdas, but in core, they get removed (and the type is still in `Result::type`)
> 
> Oh, I see. the concrete typed lambda: `\(x : X) => x` will be separated to a core lambda `\x => x` and a type `Pi X -> X`. Is it right?

Totally! ✅💯
