### ISSUE TITLE
Add prim factory?

### ISSUE THREAD

**Issue by tsao-chi** [aya-prover/aya-dev#847]
This feature is necessary for prims using Nat

**Comment by ice1000** [comment]
How to use `Nat`? I think you usually define `Nat` after all `prim`s so you inevitably have no access to `Nat`.

**Comment by imkiva** [comment]
What prims would depend on Nat? Could you give an example?

**Comment by ice1000** [comment]
> What prims would depend on Nat? Could you give an example?

String traversal, `charAt`

**Comment by ice1000** [comment]
I guess this cannot be easily done and needs further discussion
