### ISSUE TITLE
Face Coverage and InOutTerm comparison

### ISSUE THREAD

**Issue by SchrodingerZhu** [aya-prover/aya-dev#861]
As suggested in CCHM, with cubical subtype, we have a description of contractible types using `Partial` and `Sub`.

In agda, we have
```agda
partialGivesContr : {A : Set} (c : {φ : I} (u : Partial φ A) → Sub A φ u) → isContr A 
partialGivesContr c =
    ( outS (c {i0} λ ()) , λ y i → outS (c { i ∨ (~ i) } λ { (i = i1) → y ; (i = i0) → outS (c {i0} λ ()) } ) )
```

The direct translation of the above proposition into aya is the following:
```aya
prim I
prim Partial
prim Sub
prim inS
prim outS
prim intervalInv
prim intervalMax
prim intervalMin

def fixl ~  : I -> I => intervalInv

def Path (A : I -> Type) (a : A 0) (b : A 1) : Type => [| i |] A i { ~ i := a | i := b }
def infix = {A : Type} : A -> A -> Type
    | a , b => Path (\ i => A) a b
def isContr (A : Type) : Type => Sig (a : A) ** (∀ b -> a = b)

def partialGivesContr {A : Type} (c : Pi {φ : I} (u : Partial φ A) -> Sub A φ u) : isContr A =>
    ( outS (c {0} {| |}) , \ y i => outS (c { intervalMax i (~ i) } {| i := y | ~ i := outS (c {0} {| |}) |} ) )
```
However, the latter fails during type checking.

**Comment by ice1000** [comment]
I have implemented conversion for subtype rules, but it's incomplete in the sense that there needs to be a type-directed reduction for `outS x` where `x : Sub A 1 { 1 ↦ u }` to `u`. To do so, we need to add one more implicit argument to `outS` which stores the partial. Right now, Aya uses the same internal repr for both `inS` and `outS` to be engineeringly efficient, but we can change that!

**Comment by ice1000** [comment]
Fixed!!
