### ISSUE TITLE
Support projection out of conCalls

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#896]
Basically this: ![image](https://user-images.githubusercontent.com/16398479/217723945-cdd4417b-1292-478f-9dfc-b1ff6528be97.png)

The feature is analogous to projecting from a tuple. It's good because:

1. Otherwise you'll need dumb pattern matching to extract the fields
2. Usually you can just write out the field directly because _you do have that piece of information_ but why not
3. This syntax is not ambiguous to anything present or potentially useful in the future
4. It will not check for Prop-ness because, again, _you do have that piece of information_.

**Comment by imkiva** [comment]
The list now starts from index 1, which is different from other languages and our own `Vec`, since `Vec A n` means the type of indices is `Fin n`. Can we start from 0 when projecting on ConCalls?

**Comment by ice1000** [comment]
> The list now starts from index 1, which is different from other languages and our own `Vec`, since `Vec A n` means the type of indices is `Fin n`. Can we start from 0 when projecting on ConCalls?

I think of it as a way of unwrapping the constructor and think of the arguments as a sigma type. If we are going to switch to 1-based counting, then we probably should do the same for sigma types too. If you think it's reasonable then we can just do so, but without C/Java background I think 1-based counting is more intuitive.

There are good reasons to choose either way:

* 0-based is used in Java, while Aya will have Java interop in the future anyway, so we may end up having both of them
* 1-based is more intuitive for non-programmers, and yet there are programming languages using 1-based (Lua, etc.)
