### ISSUE TITLE
Literate output problems

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#912]
![image](https://user-images.githubusercontent.com/16398479/218594492-2e7cf39b-5e3f-47be-918a-85983bdb3655.png)

1. Need color for comments
2. Consecutive `\n` are squeezed into a single one
3. Need a way to import a literate file from another

**Comment by ice1000** [comment]
4. Keywords should not be bolded. I now think bolding keywords is a bad idea.

**Comment by imkiva** [comment]
1. I remember comment highlight is implemented by @HoshinoTented 

2. Maybe caused by `text.contains("\n")`?

4. We need to separate typesetting of certain tokens rather than to inline them (like HTML backend). But I don't know if it is possible in LaTeX (maybe `\newcommand`?)

**Comment by ice1000** [comment]
I've fixed 1 and 2 in a branch

**Comment by ice1000** [comment]
And for 4, yes, we could probably do that separation. You can use \newcommand

**Comment by ice1000** [comment]
Most of these are fixed

**Comment by ice1000** [comment]
Actually I think importing from a literate file shouldn't be _that_ hard. Let me think think.

**Comment by ice1000** [comment]
Let's close this for now. Literate import should be part of literating libraries
