### ISSUE TITLE
We should develop our own IDE

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#949]
I think vscode is far from being usable. The plugin ecosystem forces you to use yarn or npm, and there is no hope of avoiding frontend technologies.

Also, the language server protocol has fundamental problems, as I mentioned to several of you privately. 

All of these signals indicate that we should start making our own IDE front end. This might be an adapted version of Fleet, but it depends on JetBrains' license.

**Comment by ice1000** [comment]
This is in fact an April fools joke.

**Comment by nobodxbodon** [comment]
For me, the title and part of the content will still be taken seriously.
<img width="433" alt="Screenshot 2023-04-01 at 1 41 11 PM" src="https://user-images.githubusercontent.com/392497/229313125-5816d742-19bd-45ed-bfd4-a4325e271eed.png">

**Comment by ice1000** [comment]
> For me, the title and part of the content will still be taken seriously. <img alt="Screenshot 2023-04-01 at 1 41 11 PM" width="433" src="https://user-images.githubusercontent.com/392497/229313125-5816d742-19bd-45ed-bfd4-a4325e271eed.png">

Beware of timezones :)

**Comment by ice1000** [comment]
So turned out I fooled nobody :/

**Comment by nobodxbodon** [comment]
Well, this might become no joke one day.

**Comment by ice1000** [comment]
> Well, this might become no joke one day.

I hope so, definitely :p but it's not very feasible.
