### ISSUE TITLE
Markdown backend bug

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-dev#950]
The code (sorry, I really don't know how to markdown-in-markdown-in-markdown)
![image](https://user-images.githubusercontent.com/9902643/229361815-c6b208b9-f4e9-4219-92e4-6913c284db61.png)

is incorrectly compiled to

![image](https://user-images.githubusercontent.com/9902643/229361871-2a8c6bf9-dfb2-41c6-88ef-4cd30c064f26.png)

**Comment by ice1000** [comment]
We also erroneously removed the blank line
