### ISSUE TITLE
`atob` seems broken in vuepress

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-dev#951]
https://github.com/vuejs/vuepress/issues/3065

We should implement `atob` for server side rendering. How stupid!

**Comment by imkiva** [comment]
For yarn, this is a workaround: https://github.com/foreverRuns/vuepress-vdoing-blog/commit/29f838c3f2f07a524ba43cebbbd3229a12721a77

**Comment by imkiva** [comment]
For pnpm, I tried every mentioned solution, and none of them worked

**Comment by imkiva** [comment]
I suggest getting rid of shitty pnpm and embracing yarn. Because I really don't want to spend time on any stupid bug in frontend tools -- god knows if they will come back.

**Comment by ice1000** [comment]
What's `atob`?

**Comment by ice1000** [comment]
But we aren't using vuepress, are we? We're using vitepress

**Comment by imkiva** [comment]
Let's trigger a rebuild on our website and see if vitepress has the same problem

**Comment by imkiva** [comment]
> What's `atob`?

It's a base64 decoder. Our `Doc` stores the encoded popup text in the attribute `data-tooltip-text` of an HTML tag, to avoid possible escaping problems.
