### ISSUE TITLE
InternalException about Generalized Variables

### ISSUE THREAD

**Issue by HoshinoTented** [aya-prover/aya-dev#972]
![image](https://user-images.githubusercontent.com/25280943/236476107-b35c6fdd-a8be-4f76-8243-e9988eab3ab3.png)

**Comment by HoshinoTented** [comment]
![image](https://user-images.githubusercontent.com/25280943/236478744-c4d4afd5-8b43-45cf-ab97-10ce2a6f813c.png)
There is no `A` in `bar`'s telescope because `A` was not used in `bar`'s telescope. However, we can't just set `allowGeneralized = false` when resolving the body because we should accept `foo`.

We can generate more generalized variables after we resolve the body, but this sounds not good:
* The newly generated variables won't be appended to the `LocalCtx` of the meta which is in the telescope

**Comment by ice1000** [comment]
IMO bodies should not use generalized variables.

**Comment by ice1000** [comment]
But I think we can make it work for generalized

**Comment by HoshinoTented** [comment]
So I reopen this.
